language: crystal
crystal:
- latest
- nightly
script:
- crystal spec
- crystal spec --release --no-debug
matrix:
  allow_failures:
  - crystal: nightly
before_deploy:
  - make bin
deploy:
  provider: releases
  api_key:
    secure: GchQNkqatgxJ6pnA19B/QmumWhud3RjOQZzp+3B4ZYjdnzQ3QluT1e/K5dMgeTAIkvDFanEPuRyDpq2kbLBb9egRGJDuWgyBvYtgPgV9wmTArHsjlu7rJxxdGVgoMuFJx8XnWEychONOhVQp/Jn8xAI6+sP3svGRRTUy986X7L5ixL4Usu3iqQKBVABf5bBYuMdFr+mUuAGUtjoBXOtasQNYJ5W9L76txPRK4hNjFuJ1UgbHj8XQC3y58J7W1o71Kfjdv/vVmHpzYL00ESwCu9FfZQg0ym019NpGWRVABIgTNR5vETMzEEmJD8Chnrb/bLudX8MQxGYmnJZmfSnmwVyR2uFt76KUEWXTwZcJ+fTi25n+1BunE4piGcICOmGWPNKYLq4BiitmfXM8JgjWSMrFbnnKaj4pJEKYJhzGTtA11XiL5MWwFMvJFV7GuAWZPRqQTTRpxnNof2/2AMNgL8h3QWDSMpAh1deqQVSHYkw8cM89TFVQYpo5bRFEl/krfUupB3k9nk9EXOwQHgJhTyyiB/99oa3TaE07fxWzHRjJq4cB0gbtIlbDKhUYM6cgvAuaWa7Rr5o2itq5H0Rc65o2TuQ9aAD/GXFhjG1m1x1xADaAndDLpwcgd4BJCFQh3Y8gRiX2G8Z6adp5JtDeH1qOvixMx4wj0uZWUFFdmo4=
  file: bin/invite
  skip_cleanup: true
  on:
    repo: laithshadeed/invite-test
    tags: true
